version: "3.3"

services:
  db:
    image: postgis/postgis:15-3.3
    restart: always
    environment:
      POSTGRES_DB: busdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: bus_redis
    restart: always
    volumes:
      - redisdata:/data
    ports:
      - "6379:6379"

  app:
    build:
      context: .
      dockerfile: dockerfile
    container_name: bus_app
    restart: always
    depends_on:
      - db
      - redis
    environment:
      POSTGRES_DSN: postgresql://postgres:postgres@db:5432/busdb
      REDIS_DSN: redis://redis:6379/0
      TCP_HOST: 0.0.0.0
      TCP_PORT: 5023
      HTTP_HOST: 0.0.0.0
      HTTP_PORT: 8000
    ports:
      - "8000:8000" # FastAPI
      - "5023:5023" # GT06 TCP

volumes:
  db_data:
  redisdata:
